# Generated by Django 2.0.5 on 2018-05-09 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='企业名称')),
                ('desc', models.CharField(max_length=200, verbose_name='企业简介')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系方式')),
                ('image', models.ImageField(default='img/p1.jpg', upload_to='company/%Y/%m', verbose_name='企业图片')),
                ('admin', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='管理用户')),
            ],
            options={
                'verbose_name': '企业名称',
                'verbose_name_plural': '企业名称',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('readyto', '即将开始'), ('funding', '众筹中'), ('success', '众筹成功'), ('failed', '众筹失败')], default='funding', max_length=20, verbose_name='众筹状态')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('desc', models.CharField(max_length=200, verbose_name='项目简介')),
                ('interest_nums', models.IntegerField(default=0, verbose_name='关注人数')),
                ('support_nums', models.IntegerField(default=0, verbose_name='支持人数')),
                ('target_fund', models.IntegerField(default=100, verbose_name='目标金额')),
                ('support_fund', models.IntegerField(default=0, verbose_name='已筹资金')),
                ('deadline', models.IntegerField(default=0, verbose_name='筹资天数')),
                ('user_desc', models.CharField(max_length=100, verbose_name='自我介绍')),
                ('user_detail', models.CharField(max_length=300, verbose_name='详细自我介绍')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('service_mobile', models.CharField(max_length=20, verbose_name='客服电话')),
                ('image_first', models.ImageField(upload_to='project/%Y/%m', verbose_name='项目头图')),
                ('image_detail', models.ImageField(upload_to='project/%Y/%m', verbose_name='项目详情')),
                ('admin', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='管理用户')),
            ],
            options={
                'verbose_name': '众筹项目',
                'verbose_name_plural': '众筹项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类信息')),
                ('desc', models.CharField(max_length=30, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_category', models.CharField(choices=[('real', '实物回报'), ('virtual', '虚拟物品回报')], max_length=20, verbose_name='回报类型')),
                ('item_name', models.CharField(max_length=30, unique=True, verbose_name='回报名称')),
                ('item_value', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='支持金额')),
                ('item_freight', models.IntegerField(default=0, verbose_name='配送费用')),
                ('item_send_day', models.IntegerField(default=10, verbose_name='发放时间(天)')),
                ('item_desc', models.CharField(max_length=200, verbose_name='回报内容')),
                ('how_to_get', models.CharField(max_length=200, verbose_name='回报获得方式')),
                ('item_nums', models.IntegerField(default=0, verbose_name='回报数量')),
                ('item_image', models.ImageField(upload_to='project/%Y/%m', verbose_name='说明图片')),
                ('support_nums', models.IntegerField(default=0, verbose_name='支持人数')),
                ('up_to_buy', models.IntegerField(default=1, verbose_name='单笔限购')),
                ('invoice', models.CharField(choices=[('Y', '可开发票'), ('N', '不可开发票')], max_length=10, verbose_name='发票')),
                ('project', models.ForeignKey(on_delete='CASCADE', to='projects.Project', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '回报名称',
                'verbose_name_plural': '回报名称',
            },
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='一级标签')),
            ],
            options={
                'verbose_name': '项目标签',
                'verbose_name_plural': '项目标签',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.ProjectCategory', verbose_name='项目类别'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.Company', verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ForeignKey(on_delete='CASCADE', to='projects.ProjectTags', verbose_name='项目标签'),
        ),
    ]
