# Generated by Django 2.0.5 on 2018-05-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180510_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='item_desc',
        ),
    ]
