# Generated by Django 2.0.5 on 2018-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectitem_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='left_days',
            field=models.IntegerField(default=1, verbose_name='剩余天数'),
        ),
    ]
