# Generated by Django 2.0.5 on 2018-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_left_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='item_name',
            field=models.CharField(max_length=30, verbose_name='回报名称'),
        ),
    ]
