# Generated by Django 2.0.5 on 2018-05-12 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectcategory_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='到期日期'),
            preserve_default=False,
        ),
    ]
