# Generated by Django 2.0.5 on 2018-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayorder',
            name='order_status',
            field=models.CharField(choices=[('waiting', '待支付'), ('paid', '已支付'), ('closed', '订单关闭'), ('completed', '已完成')], default='waiting', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='userpayorder',
            name='coupon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额'),
        ),
        migrations.AlterField(
            model_name='userpayorder',
            name='pay_order_no',
            field=models.CharField(default='', max_length=100, verbose_name='付款单号'),
        ),
        migrations.AlterField(
            model_name='userpayorder',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额'),
        ),
    ]
