# Generated by Django 2.0.5 on 2018-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card_image',
            field=models.ImageField(default='', upload_to='users/%Y/%m', verbose_name='身份证照片'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card_num',
            field=models.CharField(default='', max_length=18, verbose_name='身份证'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='realname',
            field=models.CharField(default='', max_length=20, verbose_name='真实姓名'),
        ),
    ]
