# Generated by Django 2.0.5 on 2018-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='is_approval',
            field=models.BooleanField(default=False, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_approval',
            field=models.BooleanField(default=False, verbose_name='审批状态'),
        ),
    ]
