# Generated by Django 2.0.5 on 2018-05-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20180511_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifycode',
            old_name='code_type',
            new_name='send_type',
        ),
        migrations.RemoveField(
            model_name='emailverifycode',
            name='user',
        ),
    ]
